### ISSUE TITLE
convert displacement into force

### ISSUE THREAD

**Issue by yclu1214** [FranckLab/3D-VTFM#1]
Hi Mohak,

I have computed the bead displacement which is stored as bead position in each time point.
How could I change it into the displacement field vector format?  
Do I need to place the x vector value in the bead position as M_N_P in the 3D matrix?
Also, what is u{tim}{4}? the magnitude of displacement? sqrt(x^2+y^2+z^2)? 
Thanks.

Best,
Jason

**Comment by mohakpatel** [comment]
Hi Jason, 
Yes, the displacement needs to be in 3D matrix in generated using meshgrid. And u{4} refers to the magnitude of the displacement.
